export default {
  mode:"history",
  routes:[
    {
      path:"/",
      name:"Hot",
      component:()=>import("@/views/HotBlogList")
    },
    {
      path:"/rec",
      name:"Rec",
      component:()=>import("@/views/RecBlogList")
    },
    {
      path:"/new",
      name:"New",
      component:()=>import("@/views/NewestBlogList")
    },
    {
      path:"/follow",
      name:"Follow",
      component:()=>import("@/views/FollowBlogList")
    },
    {
      path:"/login",
      name:"Login",
      component:()=>import("@/views/Login")
    },
    {
      path:"/detail",
      name:"BlogDetails",
      component:()=>import("@/views/BlogDetails")
    },
    {
      path:"/userinfo",
      name:"UserInfo",
      component:()=>import("@/views/user-center/UserInfo")
    },
    {
      path:"/editor",
      name:"Editor",
      component:()=>import("@/views/Editor")
    },
    {
      path: "*", // 匹配所有路径
      name:"NotFound",
      component: () => import("@/views/NotFound")
    },
  ]
}